### ISSUE TITLE
Update avatar folder to html file. , umless dashboard activity cards can't display img

### ISSUE THREAD

**Issue by yuenci** [yuenci/Java-Car-Rental-System#14]
src/main/resources/com/example/car_rental_sys/html/contactUs/avatar

**Comment by Kaikiat1126** [comment]
![WhatsApp Image 2022-12-19 at 10 55 06](https://user-images.githubusercontent.com/92348692/208355306-0c0372fa-960e-48e6-b28a-a0908cf051fd.jpg)
before

![WhatsApp Image 2022-12-19 at 10 55 30](https://user-images.githubusercontent.com/92348692/208355330-b728ac49-3b6f-4da9-ae1f-387319756acd.jpg)
after

done
