### ISSUE TITLE
Your openAI secret key is published

### ISSUE THREAD

**Issue by oelmekki** [yuenci/Java-Car-Rental-System#26]
Hi,

Just a fair warning that you've published your API key:

https://github.com/yuenci/Java-Car-Rental-System/blob/0632522f889049d4c5fa424ddf176d8691fab7c5/target/classes/com/example/car_rental_sys/html/contactUs/openAI.py#L20

 If you have a a paying account on openAI's api and this key is still valid, it may be used to access the api while billing you. You should probably deactivate this key in openAI's dashboard and remove it from your code, using instead an environment variable or similar.

**Comment by yuenci** [comment]
Thank you for mention me!
